project_id = "ydyocznljcsimqbkfaip"

[functions.dev-profile]
verify_jwt = false

[functions.events-update]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.orders-expire-cleanup]
verify_jwt = false